// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *       Sam Padgett          - initial API and implementation
 *     Michael Fiedler      - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import javax.ws.rs.core.UriBuilder;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import com.ibm.oslc.adaptor.iotp.resources.Oslc_iotDomainConstants;
import com.ibm.oslc.adaptor.iotp.resources.Oslc_iotDomainConstants;
import com.ibm.oslc.adaptor.iotp.resources.Person;
import com.ibm.oslc.adaptor.iotp.resources.Person;
import com.ibm.oslc.adaptor.iotp.resources.DeviceInfo;
import com.ibm.oslc.adaptor.iotp.resources.Discussion;
import com.ibm.oslc.adaptor.iotp.resources.MetaData;

// Start of user code imports
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonPrimitive;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import com.ibm.oslc.adaptor.iotp.servlet.ServiceProviderCatalogSingleton;
import com.ibm.oslc.adaptor.iotp.IotpServiceProviderInfo;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
// End of user code

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(Oslc_iotDomainConstants.DEVICE_NAMESPACE)
@OslcName(Oslc_iotDomainConstants.DEVICE_LOCALNAME)
@OslcResourceShape(title = "Device Resource Shape", describes = Oslc_iotDomainConstants.DEVICE_TYPE)
public class Device
    extends Resource
    implements IDevice
{
    // Start of user code attributeAnnotation:deviceInfo
    // End of user code
    private DeviceInfo deviceInfo = new DeviceInfo();
    // Start of user code attributeAnnotation:metaData
    // End of user code
    private MetaData metaData = new MetaData();
    // Start of user code attributeAnnotation:typeId
    // End of user code
    private String typeId;
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    public Device(HttpServletRequest httpServletRequest, final IotpServiceProviderInfo info, final String typeId, final String id, JsonObject jsonObject) throws URISyntaxException {
		super(id, jsonObject);

		// Set some inherited oslc_am:Resource properties that need to be set by the subclass
		setTitle(id);
		setTypeId(typeId);
		// IoT Platform resources need to be marked with rdf:types that the CLM apps can link to
		// All cross-server links are fixed and hard-coded, so we have to do this to create any links
		// This is also influenced by where the links can be stored - either directly or as backlinks
		getTypes().add(new URI("http://open-services.net/ns/cm#ChangeRequest"));		
		getTypes().add(new URI("http://open-services.net/ns/rm#Requirement"));		

		ServiceProvider serviceProvider = ServiceProviderCatalogSingleton.getIotpServiceProvider(httpServletRequest, info.iotId);
		HashSet<URI> serviceProviders = new HashSet<URI>();
		serviceProviders.add(serviceProvider.getAbout());
		setServiceProvider(serviceProviders);
		setAbout(constructURI(info.iotId, typeId, id));
		try {
			setInstanceShape(createResourceShape().getAbout());
		} catch (OslcCoreApplicationException e) {
		}

		
		JsonElement element = jsonObject.get("typeId");
		if (element != null) this.setTypeId(element.getAsString());

		JsonObject devInfo = jsonObject.get("deviceInfo").getAsJsonObject();
		if (element != null) {
			element = devInfo.get("serialNumber");
			if (element != null) deviceInfo.setSerialNumber(element.getAsString());
			element = devInfo.get("manufacturer");
			if (element != null) deviceInfo.setManufacturer(element.getAsString());
			element = devInfo.get("model");
			if (element != null) deviceInfo.setModel(element.getAsString());
			element = devInfo.get("deviceClass");
			if (element != null) deviceInfo.setDeviceClass(element.getAsString());
			element = devInfo.get("description");
			if (element != null) deviceInfo.setDescription(element.getAsString());
			if (element != null) this.setDescription(element.getAsString());
			element = devInfo.get("fwVersion");
			if (element != null) deviceInfo.setFwVersion(element.getAsString());
			element = devInfo.get("hwVersion");
			if (element != null) deviceInfo.setHwVersion(element.getAsString());
			element = devInfo.get("descriptiveLocation");
			if (element != null) deviceInfo.setDescriptiveLocation(element.getAsString());
		}
		
		element = jsonObject.get("metadata");
		if (element != null) {
			for (Map.Entry<String, JsonElement> entry : element.getAsJsonObject().entrySet()) {
				MetaProperty prop = new MetaProperty();
				prop.setName(entry.getKey());
				prop.setValue(entry.getValue().getAsString());
				metaData.addMetaProperties(prop);
			}
		}
    }
    
    public JsonElement toJson() {
		JsonObject json = super.toJson().getAsJsonObject();
		
		json.addProperty("deviceId", getIdentifier());
		json.addProperty("typeId", getTypeId());
		if (deviceInfo != null) {
			JsonObject deviceInfoJson = new JsonObject();
			deviceInfoJson.addProperty("serialNumber", deviceInfo.getSerialNumber());
			deviceInfoJson.addProperty("manufacturer", deviceInfo.getManufacturer());
			deviceInfoJson.addProperty("model", deviceInfo.getModel());
			deviceInfoJson.addProperty("deviceClass", deviceInfo.getDeviceClass());
			deviceInfoJson.addProperty("description", deviceInfo.getDescription());
			deviceInfoJson.addProperty("fwVersion", deviceInfo.getFwVersion());
			deviceInfoJson.addProperty("hwVersion", deviceInfo.getHwVersion());
			deviceInfoJson.addProperty("descriptiveLocation", deviceInfo.getDescriptiveLocation());
			json.add("deviceInfo", deviceInfoJson);
		}
		if (metaData != null && metaData.getMetaProperties().size() > 0)  {
			JsonObject metaDataJson = new JsonObject();
			for (MetaProperty prop : metaData.getMetaProperties()) {
				metaDataJson.addProperty(prop.getName(), prop.getValue());
			}
			json.add("metadata", metaDataJson);
		}
		return json;
    }
    // End of user code
    public Device()
           throws URISyntaxException
    {
        super();
    
        // Start of user code constructor1
        // End of user code
    }
    
    public Device(final URI about)
           throws URISyntaxException
    {
        super(about);
    
        // Start of user code constructor2
        // End of user code
    }
    
    /**
    * @deprecated Use the methods in class {@link com.ibm.oslc.adaptor.iotp.CE4IoTConnectorResourcesFactory} instead.
    */
    @Deprecated
    public Device(final String iotId, final String typeId, final String deviceId)
           throws URISyntaxException
    {
        this (constructURI(iotId, typeId, deviceId));
        // Start of user code constructor3
        // End of user code
    }
    
    /**
    * @deprecated Use the methods in class {@link com.ibm.oslc.adaptor.iotp.CE4IoTConnectorResourcesFactory} instead.
    */
    @Deprecated
    public static URI constructURI(final String iotId, final String typeId, final String deviceId)
    {
        String basePath = OSLC4JUtils.getServletURI();
        Map<String, Object> pathParameters = new HashMap<String, Object>();
        pathParameters.put("iotId", iotId);
        pathParameters.put("typeId", typeId);
        pathParameters.put("deviceId", deviceId);
        String instanceURI = "iotp/{iotId}/resources/devices/{typeId}/devices/{deviceId}";
    
        final UriBuilder builder = UriBuilder.fromUri(basePath);
        return builder.path(instanceURI).buildFromMap(pathParameters);
    }
    
    /**
    * @deprecated Use the methods in class {@link com.ibm.oslc.adaptor.iotp.CE4IoTConnectorResourcesFactory} instead.
    */
    @Deprecated
    public static Link constructLink(final String iotId, final String typeId, final String deviceId , final String label)
    {
        return new Link(constructURI(iotId, typeId, deviceId), label);
    }
    
    /**
    * @deprecated Use the methods in class {@link com.ibm.oslc.adaptor.iotp.CE4IoTConnectorResourcesFactory} instead.
    */
    @Deprecated
    public static Link constructLink(final String iotId, final String typeId, final String deviceId)
    {
        return new Link(constructURI(iotId, typeId, deviceId));
    }
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        Oslc_iotDomainConstants.DEVICE_PATH,
        Device.class);
    }
    
    
    public String toString()
    {
        return toString(false);
    }
    
    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code
    
        if (asLocalResource) {
            result = result + "{a Local Device Resource} - update Device.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = getAbout().toString();
        }
    
        // Start of user code toString_finalize
        result = getTitle();
        // End of user code
    
        return result;
    }
    
    public String toHtml()
    {
        return toHtml(false);
    }
    
    public String toHtml(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toHtml_init
        // End of user code
    
        if (asLocalResource) {
            result = toString(true);
            // Start of user code toHtml_bodyForLocalResource
            // End of user code
        }
        else {
            result = "<a href=\"" + getAbout() + "\" class=\"oslc-resource-link\">" + toString() + "</a>";
        }
    
        // Start of user code toHtml_finalize
        // End of user code
    
        return result;
    }
    
    
    // Start of user code getterAnnotation:deviceInfo
    // End of user code
    @OslcName("deviceInfo")
    @OslcPropertyDefinition(Oslc_iotDomainConstants.IOT_PLATFORM_NAMSPACE + "deviceInfo")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.LocalResource)
    @OslcRange({Oslc_iotDomainConstants.DEVICEINFO_TYPE})
    @OslcReadOnly(false)
    @OslcTitle("deviceInfo")
    public DeviceInfo getDeviceInfo()
    {
        // Start of user code getterInit:deviceInfo
        // End of user code
        return deviceInfo;
    }
    
    // Start of user code getterAnnotation:metaData
    // End of user code
    @OslcName("metaData")
    @OslcPropertyDefinition(Oslc_iotDomainConstants.IOT_PLATFORM_NAMSPACE + "metaData")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.LocalResource)
    @OslcRange({Oslc_iotDomainConstants.METADATA_TYPE})
    @OslcReadOnly(false)
    @OslcTitle("metaData")
    public MetaData getMetaData()
    {
        // Start of user code getterInit:metaData
        // End of user code
        return metaData;
    }
    
    // Start of user code getterAnnotation:typeId
    // End of user code
    @OslcName("typeId")
    @OslcPropertyDefinition(Oslc_iotDomainConstants.IOT_PLATFORM_NAMSPACE + "typeId")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("typeId")
    public String getTypeId()
    {
        // Start of user code getterInit:typeId
        // End of user code
        return typeId;
    }
    
    
    // Start of user code setterAnnotation:deviceInfo
    // End of user code
    public void setDeviceInfo(final DeviceInfo deviceInfo )
    {
        // Start of user code setterInit:deviceInfo
        // End of user code
        this.deviceInfo = deviceInfo;
    
        // Start of user code setterFinalize:deviceInfo
        // End of user code
    }
    
    // Start of user code setterAnnotation:metaData
    // End of user code
    public void setMetaData(final MetaData metaData )
    {
        // Start of user code setterInit:metaData
        // End of user code
        this.metaData = metaData;
    
        // Start of user code setterFinalize:metaData
        // End of user code
    }
    
    // Start of user code setterAnnotation:typeId
    // End of user code
    public void setTypeId(final String typeId )
    {
        // Start of user code setterInit:typeId
        // End of user code
        this.typeId = typeId;
    
        // Start of user code setterFinalize:typeId
        // End of user code
    }
    
    
    static public String deviceInfoToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:deviceInfoToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"deviceInfo\">deviceInfo: </LABEL>";
    
        // Start of user code "Mid:deviceInfoToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:deviceInfoToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String metaDataToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:metaDataToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"metaData\">metaData: </LABEL>";
    
        // Start of user code "Mid:metaDataToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:metaDataToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String typeIdToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:typeIdToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"typeId\">typeId: </LABEL>";
    
        // Start of user code "Mid:typeIdToHtmlForCreation(...)"
        // End of user code
    
        s= s + "<input name=\"typeId\" type=\"text\" style=\"width: 400px\" id=\"typeId\" >";
        // Start of user code "Finalize:typeIdToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    
    public String deviceInfoToHtml()
    {
        String s = "";
    
        // Start of user code deviceInfotoHtml_mid
        // End of user code
    
        try {
            if (deviceInfo == null) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + deviceInfo.toHtml(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code deviceInfotoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String metaDataToHtml()
    {
        String s = "";
    
        // Start of user code metaDatatoHtml_mid
        // End of user code
    
        try {
            if (metaData == null) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + metaData.toHtml(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code metaDatatoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String typeIdToHtml()
    {
        String s = "";
    
        // Start of user code typeIdtoHtml_mid
        // End of user code
    
        try {
            if (typeId == null) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + typeId.toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code typeIdtoHtml_finalize
        // End of user code
    
        return s;
    }
    
    
}
