// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public interface Oslc_bmxDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String BLUEMIX_DOMAIN = "http://jazz.net/ns/bmx#";
    public static String BLUEMIX_NAMSPACE = "http://jazz.net/ns/bmx#";
    public static String BLUEMIX_NAMSPACE_PREFIX = "oslc_bmx";

    public static String APP = "App";
    public static String PATH_APP = "app";
    public static String TYPE_APP = BLUEMIX_NAMSPACE + APP;
    public static String CFSERVICE = "CFService";
    public static String PATH_CFSERVICE = "cFService";
    public static String TYPE_CFSERVICE = BLUEMIX_NAMSPACE + CFSERVICE;
    public static String FLOW = "Flow";
    public static String PATH_FLOW = "flow";
    public static String TYPE_FLOW = BLUEMIX_NAMSPACE + FLOW;
    public static String NODEREDAPP = "NodeREDApp";
    public static String PATH_NODEREDAPP = "nodeREDApp";
    public static String TYPE_NODEREDAPP = BLUEMIX_NAMSPACE + NODEREDAPP;
    public static String SPACE = "Space";
    public static String PATH_SPACE = "space";
    public static String TYPE_SPACE = BLUEMIX_NAMSPACE + SPACE;
}
