// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public interface OslcDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String OSLC_DOMAIN = "http://open-services.net/ns/core#";
    public static String OSLC_NAMSPACE = "http://open-services.net/ns/core#";
    public static String OSLC_NAMSPACE_PREFIX = "oslc";

    public static String ALLOWEDVALUES = "AllowedValues";
    public static String PATH_ALLOWEDVALUES = "allowedValues";
    public static String TYPE_ALLOWEDVALUES = OSLC_NAMSPACE + ALLOWEDVALUES;
    public static String DISCUSSION = "Discussion";
    public static String PATH_DISCUSSION = "discussion";
    public static String TYPE_DISCUSSION = OSLC_NAMSPACE + DISCUSSION;
    public static String PROPERTY = "Property";
    public static String PATH_PROPERTY = "property";
    public static String TYPE_PROPERTY = OSLC_NAMSPACE + PROPERTY;
    public static String RESOURCESHAPE = "ResourceShape";
    public static String PATH_RESOURCESHAPE = "resourceShape";
    public static String TYPE_RESOURCESHAPE = OSLC_NAMSPACE + RESOURCESHAPE;
    public static String SERVICEPROVIDER = "ServiceProvider";
    public static String PATH_SERVICEPROVIDER = "serviceProvider";
    public static String TYPE_SERVICEPROVIDER = OSLC_NAMSPACE + SERVICEPROVIDER;
}
