// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_iotDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String IOT_PLATFORM_DOMAIN = "http://jazz.net/ns/iot#";
    public static String IOT_PLATFORM_NAMSPACE = "http://jazz.net/ns/iot#";
    public static String IOT_PLATFORM_NAMSPACE_PREFIX = "oslc_iot";

    public static String DEVICE_PATH = "device";
    public static String DEVICE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DEVICE_LOCALNAME = "Device"; //localName of the rdfs:class the resource describes
    public static String DEVICE_TYPE = DEVICE_NAMESPACE + DEVICE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String DEVICEINFO_PATH = "deviceInfo";
    public static String DEVICEINFO_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DEVICEINFO_LOCALNAME = "DeviceInfo"; //localName of the rdfs:class the resource describes
    public static String DEVICEINFO_TYPE = DEVICEINFO_NAMESPACE + DEVICEINFO_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String DEVICETYPE_PATH = "deviceType";
    public static String DEVICETYPE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DEVICETYPE_LOCALNAME = "DeviceType"; //localName of the rdfs:class the resource describes
    public static String DEVICETYPE_TYPE = DEVICETYPE_NAMESPACE + DEVICETYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String DEVICETYPEMAPPING_PATH = "deviceTypeMapping";
    public static String DEVICETYPEMAPPING_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DEVICETYPEMAPPING_LOCALNAME = "DeviceTypeMapping"; //localName of the rdfs:class the resource describes
    public static String DEVICETYPEMAPPING_TYPE = DEVICETYPEMAPPING_NAMESPACE + DEVICETYPEMAPPING_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String EVENTTYPE_PATH = "eventType";
    public static String EVENTTYPE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String EVENTTYPE_LOCALNAME = "EventType"; //localName of the rdfs:class the resource describes
    public static String EVENTTYPE_TYPE = EVENTTYPE_NAMESPACE + EVENTTYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String LOGICALINTERFACE_PATH = "logicalInterface";
    public static String LOGICALINTERFACE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String LOGICALINTERFACE_LOCALNAME = "LogicalInterface"; //localName of the rdfs:class the resource describes
    public static String LOGICALINTERFACE_TYPE = LOGICALINTERFACE_NAMESPACE + LOGICALINTERFACE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String METADATA_PATH = "metaData";
    public static String METADATA_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String METADATA_LOCALNAME = "MetaData"; //localName of the rdfs:class the resource describes
    public static String METADATA_TYPE = METADATA_NAMESPACE + METADATA_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String METAPROPERTY_PATH = "metaProperty";
    public static String METAPROPERTY_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String METAPROPERTY_LOCALNAME = "MetaProperty"; //localName of the rdfs:class the resource describes
    public static String METAPROPERTY_TYPE = METAPROPERTY_NAMESPACE + METAPROPERTY_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PHYSICALINTERFACE_PATH = "physicalInterface";
    public static String PHYSICALINTERFACE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PHYSICALINTERFACE_LOCALNAME = "PhysicalInterface"; //localName of the rdfs:class the resource describes
    public static String PHYSICALINTERFACE_TYPE = PHYSICALINTERFACE_NAMESPACE + PHYSICALINTERFACE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String RULE_PATH = "rule";
    public static String RULE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String RULE_LOCALNAME = "Rule"; //localName of the rdfs:class the resource describes
    public static String RULE_TYPE = RULE_NAMESPACE + RULE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String SCHEMA_PATH = "schema";
    public static String SCHEMA_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String SCHEMA_LOCALNAME = "Schema"; //localName of the rdfs:class the resource describes
    public static String SCHEMA_TYPE = SCHEMA_NAMESPACE + SCHEMA_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String THING_PATH = "thing";
    public static String THING_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String THING_LOCALNAME = "Thing"; //localName of the rdfs:class the resource describes
    public static String THING_TYPE = THING_NAMESPACE + THING_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String THINGTYPE_PATH = "thingType";
    public static String THINGTYPE_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String THINGTYPE_LOCALNAME = "ThingType"; //localName of the rdfs:class the resource describes
    public static String THINGTYPE_TYPE = THINGTYPE_NAMESPACE + THINGTYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String THINGTYPEMAPPING_PATH = "thingTypeMapping";
    public static String THINGTYPEMAPPING_NAMESPACE = IOT_PLATFORM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String THINGTYPEMAPPING_LOCALNAME = "ThingTypeMapping"; //localName of the rdfs:class the resource describes
    public static String THINGTYPEMAPPING_TYPE = THINGTYPEMAPPING_NAMESPACE + THINGTYPEMAPPING_LOCALNAME; //fullname of the rdfs:class the resource describes
}
