// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public interface Oslc_iotDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String IOT_PLATFORM_DOMAIN = "http://jazz.net/ns/iot#";
    public static String IOT_PLATFORM_NAMSPACE = "http://jazz.net/ns/iot#";
    public static String IOT_PLATFORM_NAMSPACE_PREFIX = "oslc_iot";

    public static String DEVICE = "Device";
    public static String PATH_DEVICE = "device";
    public static String TYPE_DEVICE = IOT_PLATFORM_NAMSPACE + DEVICE;
    public static String DEVICEINFO = "DeviceInfo";
    public static String PATH_DEVICEINFO = "deviceInfo";
    public static String TYPE_DEVICEINFO = IOT_PLATFORM_NAMSPACE + DEVICEINFO;
    public static String DEVICETYPE = "DeviceType";
    public static String PATH_DEVICETYPE = "deviceType";
    public static String TYPE_DEVICETYPE = IOT_PLATFORM_NAMSPACE + DEVICETYPE;
    public static String DEVICETYPEMAPPING = "DeviceTypeMapping";
    public static String PATH_DEVICETYPEMAPPING = "deviceTypeMapping";
    public static String TYPE_DEVICETYPEMAPPING = IOT_PLATFORM_NAMSPACE + DEVICETYPEMAPPING;
    public static String EVENTTYPE = "EventType";
    public static String PATH_EVENTTYPE = "eventType";
    public static String TYPE_EVENTTYPE = IOT_PLATFORM_NAMSPACE + EVENTTYPE;
    public static String LOGICALINTERFACE = "LogicalInterface";
    public static String PATH_LOGICALINTERFACE = "logicalInterface";
    public static String TYPE_LOGICALINTERFACE = IOT_PLATFORM_NAMSPACE + LOGICALINTERFACE;
    public static String METADATA = "MetaData";
    public static String PATH_METADATA = "metaData";
    public static String TYPE_METADATA = IOT_PLATFORM_NAMSPACE + METADATA;
    public static String METAPROPERTY = "MetaProperty";
    public static String PATH_METAPROPERTY = "metaProperty";
    public static String TYPE_METAPROPERTY = IOT_PLATFORM_NAMSPACE + METAPROPERTY;
    public static String PHYSICALINTERFACE = "PhysicalInterface";
    public static String PATH_PHYSICALINTERFACE = "physicalInterface";
    public static String TYPE_PHYSICALINTERFACE = IOT_PLATFORM_NAMSPACE + PHYSICALINTERFACE;
    public static String RULE = "Rule";
    public static String PATH_RULE = "rule";
    public static String TYPE_RULE = IOT_PLATFORM_NAMSPACE + RULE;
    public static String SCHEMA = "Schema";
    public static String PATH_SCHEMA = "schema";
    public static String TYPE_SCHEMA = IOT_PLATFORM_NAMSPACE + SCHEMA;
    public static String THING = "Thing";
    public static String PATH_THING = "thing";
    public static String TYPE_THING = IOT_PLATFORM_NAMSPACE + THING;
    public static String THINGTYPE = "ThingType";
    public static String PATH_THINGTYPE = "thingType";
    public static String TYPE_THINGTYPE = IOT_PLATFORM_NAMSPACE + THINGTYPE;
    public static String THINGTYPEMAPPING = "ThingTypeMapping";
    public static String PATH_THINGTYPEMAPPING = "thingTypeMapping";
    public static String TYPE_THINGTYPEMAPPING = IOT_PLATFORM_NAMSPACE + THINGTYPEMAPPING;
}
