<!DOCTYPE html>
<%--Start of user code "Copyright"
--%>
<%--
 Copyright (c) 2011, 2012 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 Contributors:

  Sam Padgett     - initial API and implementation
  Michael Fiedler - adapted for OSLC4J
  Jad El-khoury   - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>
<%--End of user code--%>

<%--Start of user code "body"
--%>
<%--TODO: Replace/adjust this default content as necessary.
All manual changes in this "protected" user code area will NOT be overwritten upon subsequent code generations.
To revert to the default generated content, delete all content in this file, and then re-generate.
--%>

<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="java.util.List" %>
<%@page import="com.ibm.oslc.adaptor.iotp.resources.Resource"%>
<%@page import="com.ibm.oslc.adaptor.iotp.resources.ChangeRequest"%>
<%@page import="com.ibm.oslc.adaptor.iotp.resources.Requirement"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="javax.ws.rs.core.UriBuilder"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  String creatorUri = (String) request.getAttribute("creatorUri");
  String iotId = (String) request.getAttribute("iotId");
%>

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>ResourceCreationDialog</title>
    <script type="text/javascript" src="<%=UriBuilder.fromUri(OSLC4JUtils.getPublicURI()).path("delegatedUI.js").build().toString()%>"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script>
  var creatorUri = {}
  $(document).ready(function() {
	    var selectType = document.getElementById("selectType")
	    $('#selectType').on('click', function load() {
	    	var type = selectType.options[selectType.selectedIndex].value
	      	var parser = document.createElement('a')
	    	parser.href = document.URL
	    	var uri = parser.protocol+'//'+parser.host+'/iotp/creators/'+type+'.jsp'
		    creatorUri = '<%= creatorUri %>'+'?type='+type  // provide the selected type as a query parameter
	    	$('#Create #resourceProperties').load(uri)	  
	     })
	     selectType.selectedIndex = 1
	     selectType.click()
	  })
  </script>
  </head>
  <body style="padding: 10px;">
  Type: <select id="selectType">
  	<option value="device">Device</option>
  	<option value="devicetype">DeviceType</option>
  	<option value="thing">Thing</option>
  	<option value="thingtype">ThingType</option>
  	<option value="logicalinterface">LogicalInterface</option>
  	<option value="physicalinterface">PhysicalInterface</option>
  	<option value="eventtype">EventType</option>
  	<option value="schema">Schema</option>
  	<option value="rule">Rule</option>  	
  </select>
    <div id="bugzilla-body">
    <form id="Create" method="POST" class="enter_bug_form">
    	<div id="resourceProperties"></div>
      </form>
      <div style="clear: both;"></div>
    </div>
  </body>
</html>
<%--End of user code--%>
