// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.ibm.oslc.adaptor.iotp.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_bmxDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String BLUEMIX_DOMAIN = "http://jazz.net/ns/bmx#";
    public static String BLUEMIX_NAMSPACE = "http://jazz.net/ns/bmx#";
    public static String BLUEMIX_NAMSPACE_PREFIX = "oslc_bmx";

    public static String APP_PATH = "app";
    public static String APP_NAMESPACE = BLUEMIX_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String APP_LOCALNAME = "App"; //localName of the rdfs:class the resource describes
    public static String APP_TYPE = APP_NAMESPACE + APP_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String CFSERVICE_PATH = "cFService";
    public static String CFSERVICE_NAMESPACE = BLUEMIX_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String CFSERVICE_LOCALNAME = "CFService"; //localName of the rdfs:class the resource describes
    public static String CFSERVICE_TYPE = CFSERVICE_NAMESPACE + CFSERVICE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String FLOW_PATH = "flow";
    public static String FLOW_NAMESPACE = BLUEMIX_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String FLOW_LOCALNAME = "Flow"; //localName of the rdfs:class the resource describes
    public static String FLOW_TYPE = FLOW_NAMESPACE + FLOW_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String NODEREDAPP_PATH = "nodeREDApp";
    public static String NODEREDAPP_NAMESPACE = BLUEMIX_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String NODEREDAPP_LOCALNAME = "NodeREDApp"; //localName of the rdfs:class the resource describes
    public static String NODEREDAPP_TYPE = NODEREDAPP_NAMESPACE + NODEREDAPP_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String SPACE_PATH = "space";
    public static String SPACE_NAMESPACE = BLUEMIX_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String SPACE_LOCALNAME = "Space"; //localName of the rdfs:class the resource describes
    public static String SPACE_TYPE = SPACE_NAMESPACE + SPACE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
