<!DOCTYPE html>
<%--Start of user code "Copyright"
--%>
<%--
 Copyright (c) 2011, 2012 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 Contributors:

  Sam Padgett     - initial API and implementation
  Michael Fiedler - adapted for OSLC4J
  Jad El-khoury   - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>
<%--End of user code--%>

<%--Start of user code "body"
--%>
<%--TODO: Replace/adjust this default content as necessary.
All manual changes in this "protected" user code area will NOT be overwritten upon subsequent code generations.
To revert to the default generated content, delete all content in this file, and then re-generate.
--%>

<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="java.util.List" %>
<%@page import="com.ibm.oslc.adaptor.iotp.resources.Thing"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="javax.ws.rs.core.UriBuilder"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  String creatorUri = (String) request.getAttribute("creatorUri");
  String iotId = (String) request.getAttribute("iotId");
%>

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>ThingCreationDialog</title>
    <script type="text/javascript" src="<%=UriBuilder.fromUri(OSLC4JUtils.getPublicURI()).path("delegatedUI.js").build().toString()%>"></script>
  </head>
  <body style="padding: 10px;">
    <div id="bugzilla-body">
    <form id="Create" method="POST" class="enter_bug_form">
        <table style="clear: both;">
          <tr>
            <td><%= Thing.thingTypesToHtmlForCreation1(request, iotId)%></td>
          </tr>
          <tr>
            <td><%= Thing.descriptionToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.identifierToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.shortTitleToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.titleToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.contributorToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.creatorToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.subjectToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.createdToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.modifiedToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.typeToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.discussedByToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.instanceShapeToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.serviceProviderToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td><%= Thing.relationToHtmlForCreation(request)%></td>
          </tr>
          <tr>
            <td></td>
            <td>
              <input type="button"
                value="Submit"
                onclick="javascript: create( '<%= creatorUri %>' )">
              <input type="reset">
            </td>
          </tr>
        </table>
        <div style="width: 500px;">
        </div>
      </form>

      <div style="clear: both;"></div>
    </div>
  </body>
</html>
<%--End of user code--%>
